apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.label }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.pod.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.pod.label }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          imagePullPolicy: Always
